[versions]
# (common)
choco-networking = "0.1.3"
jetbrains-annotations = "24.1.0"
junit = "5.13.4"

# (bukkit)
anticheat-aac = "0.0.1-SNAPSHOT"
anticheat-grim = "d99dcba158" # The last API version before their "platform independence" update, which changes the package of their FlagEvent!
anticheat-intave = "14.4.2"
anticheat-matrix = "317d4635fd" # This repository is dead now, but we're going to keep using it because it exists on JitPack :)
anticheat-nocheatplus = "3.16.1-SNAPSHOT"
anticheat-polar = "2.0.0"
anticheat-spartan = "1.0"
anticheat-light = "99d1930f2a" # https://github.com/tiredvekster/LightAntiCheat/commit/99d1930f2afa0e5dd23a5e212aadf49499e3fd83
anticheat-negativity = "2.7.1"
anticheat-themis = "0.0.1-SNAPSHOT"
anticheat-vulcan = "2.9.1"
bstats = "3.0.2"
jobs = "v5.2.2.3" # Higher versions require Java 21
mcmmo = "2.1.228"
placeholder-api = "2.11.5"
spigot-api = "1.17.1-R0.1-SNAPSHOT"
vault-api = "1.7"
worldguard = "7.0.9" # Higher versions require Java 21

# (fabric)
fabric-api = "0.140.0+1.21.11"
fabric-loader = "0.18.3"
minecraft = "1.21.11"

# plugins
fabric-loom = "1.13-SNAPSHOT"
shadow = "9.2.0"

[libraries]
# (common)
choco-networking-common = { module = "wtf.choco:networking-common", version.ref = "choco-networking" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

# (bukkit)
anticheat-aac = { module = "me.konsolas:AACAPIDummy", version.ref = "anticheat-aac" } # Dummy API artifact, contains only add/removeExemption() and AACExemption classes useful to VeinMiner!
anticheat-grim = { module = "ac.grim.grimac:GrimAPI", version.ref = "anticheat-grim" }
anticheat-intave = { module = "com.github.intave:access", version.ref = "anticheat-intave" }
anticheat-matrix = { module = "com.github.jiangdashao:matrix-api-repo", version.ref = "anticheat-matrix" }
anticheat-nocheatplus = { module = "fr.neatmonster:nocheatplus", version.ref = "anticheat-nocheatplus" }
anticheat-polar = { module = "top.polar:api", version.ref = "anticheat-polar" }
anticheat-spartan = { module = "me.vagdedes:SpartanAPI", version.ref = "anticheat-spartan" }
anticheat-light = { module = "com.github.tiredvekster:LightAntiCheat", version.ref = "anticheat-light" }
anticheat-negativity = { module = "com.github.Elikill58:Negativity", version.ref = "anticheat-negativity" }
anticheat-vulcan = { module = "me.frep:VulcanAPI", version.ref = "anticheat-vulcan" }
anticheat-themis = { module = "com.gmail.olexorous:ThemisAPIDummy", version.ref = "anticheat-themis" } # Dummy API artifact, contains only ViolationEvent and its methods useful to VeinMiner!
bstats-base = { module = "org.bstats:bstats-base", version.ref = "bstats" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
choco-networking-bukkit = { module = "wtf.choco:networking-bukkit", version.ref = "choco-networking" }
mcmmo = { module = "com.gmail.nossr50.mcMMO:mcMMO", version.ref = "mcmmo" }
jobs = { module = "com.github.Zrips:Jobs", version.ref = "jobs" }
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
vault-api = { module = "net.milkbowl.vault:VaultAPI", version.ref = "vault-api" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

# (fabric)
choco-networking-fabric = { module = "wtf.choco:networking-fabric", version.ref = "choco-networking" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
